### ISSUE TITLE
CARICAMENTO IMMAGINE

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#11]
Non so come si fa a farlo...manca in nuova disciplina

**Comment by donatocatalano** [comment]
ho dato un'occhiata ma non sto più connettendo

**Comment by giovannidefilippi** [comment]
Bisogna prima caricare l'immagine nella cartella img del progetto. Poi il responsabile indica nel form il nome completo di estensione dell'immagine e salva...se l'immagine c'è la carica..adesso modifico il form..

**Comment by donatocatalano** [comment]
Quindi non la prende da una directory a scelta...tipo dal desktop

**Comment by giovannidefilippi** [comment]
no troppo difficile...si potrebbe fare mettendo il percorso del file per intero nel db...il db acquisisce solo il nome del file non il file per intero..

**Comment by giovannidefilippi** [comment]
Nuova disciplina ora ok...passo e chiudo issue..Se vuoi provare metti il nome file immagine fitness.jpg

**Comment by donatocatalano** [comment]
Ok domani vediamo
