### ISSUE TITLE
MANCA STAMPA PDF

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#12]
In iscrizioni corsi manca questa funzione...e visualizzazione corsi a cui iscriversi

**Comment by giovannidefilippi** [comment]
Creato file di testo...ora inglobo file.java che fa la stampa pdf

**Comment by donatocatalano** [comment]
inoltre quando crea il file di testo da cui stampare dovrebbe cancellarlo ogni volta e farne uno nuovo perchè così non cancella le selezioni precedenti...
(questo solo nel caso in cui si stampa la distinta due volte consecutivamente)

**Comment by donatocatalano** [comment]
comunque funziona...per me va bene credo

**Comment by giovannidefilippi** [comment]
Quando chiama la stampa sovrascrive il contenuto del file vecchio...la stampa va fatta dopo aver confermato le modifiche cliccando prima "invia prenotazione"...chiudo
