### ISSUE TITLE
manca inserimento nuova testimonianza

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#15]
Manca un po' tutto...ascoltatore per il JOptionMessage ecc

**Comment by donatocatalano** [comment]
e soprattutto non so come passare la data del giorno in cui viene lasciata la testimonianza

**Comment by donatocatalano** [comment]
fatto ma resta problema della data del giorno e in più non so come fare in modo che se il campo nel Joption panel Input dialog rimane vuoto blocca il flusso e non entra nell'if con il jOption dialog...

(il feedback vuoto comunque non viene inserito in ogni caso se campo vuoto ma vorrei evitare comunque che mi vada nell'if...se non mi sono spiegato poi ti dico)

**Comment by giovannidefilippi** [comment]
Si usa curdate()  direttamente in mysql ,lo facciamo domani..

**Comment by donatocatalano** [comment]
chiuso
