### ISSUE TITLE
problema in UTENTE DAO inserimento dataodierna nel db

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#18]
ho scritto la funzione e convertito data...mi stampa quella corretta ma restituisce un errore quando  fa l'insert

**Comment by giovannidefilippi** [comment]
si fa direttamente in mysql domani vediamo insieme ...nel progetto mio dell'esame c'è..

**Comment by donatocatalano** [comment]
currentdate RISOLTO
