### ISSUE TITLE
problema login

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#2]
C'è un problema con il login. Se a fare il login è un responsabile o un istruttore oltre al messaggio di benvenuto restituisce il messaggio "Utente non riconosciuto".

Non voglio risolvere con un break negli if (che comunque non si può mettere), di responsabile e istruttore, del listner quindi provo a fare qualche prova.

**Comment by giovannidefilippi** [comment]
Così va . Ho modificato il listener e le classi legate all'utente aggiungendo la variabile tesseratoEsiste,il codice così  è più pulito(ho provato altre strade ma non veniva bene)
