### ISSUE TITLE
PROBLEMA FormModDisciplina

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#21]
Credo che stia sbagliando a richiamare la disciplina

**Comment by donatocatalano** [comment]
sistemato ma non so come passare un double in stringa per il costo

**Comment by donatocatalano** [comment]
risolto Double.toString(disciplina.getCostoMensile()

**Comment by donatocatalano** [comment]
errore di sintassi sql nell'update in DB...
non capisco...ho fatto come per utente!

**Comment by giovannidefilippi** [comment]
controlla la query

**Comment by donatocatalano** [comment]
si l'ho controllata infatti...ho seguito la modalità di aggiornamento per l'utente...sul db funziona...boh...poi guardo in un altro momento...magari mi viene

**Comment by giovannidefilippi** [comment]
Risolto era la query...

**Comment by donatocatalano** [comment]
ok...lo so che era la query...comunque sto facendo un bel po' di modifiche...spero di non incasinarci
