### ISSUE TITLE
Area Autorizzazioni

### ISSUE THREAD

**Issue by giovannidefilippi** [donatocatalano/centrosportivo#22]
Ripulito zona Autorizzazioni pagamento dagli errori. Manca la parte dei valori da visualizzare..

**Comment by donatocatalano** [comment]
li ho inseriti...stavo completando...ora dobbiamo solo decidere che altri valori visualizzare...per ora ho messo solo utente e metodo di pagamento

**Comment by giovannidefilippi** [comment]
Va gia bene potremmo mettere Disciplina e livello..ma anche no

**Comment by donatocatalano** [comment]
anche no allora

**Comment by donatocatalano** [comment]
concentriamoci su quello che manca davvero
