### ISSUE TITLE
PROBLEMA IF IN AREAPRENOTAZIONI

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#24]
ho fatto una prova in base a quello che cercavo di spiegarti su whatsapp...vedi che ne pensi...magari se vedi cosa intendevo ci capiamo meglio...se pensi che non vada bene cambiamo

tra l'altro c'è un problema logico nella condizione if...
con
if(iscrizioni.get(j).getUtente()==tesserato.getIdUtente()&& iscrizioni.get(j).getAccettata()==true) RESTITUISCE ERRORE E NON FUNZIONA ASCOLTATORE
con
if(iscrizioni.get(j).getUtente()==tesserato.getIdUtente()&&iscrizioni.get(j).getDataConferma()!=null) 
NON DA ERRORI MA NON ENTRA MAI NELLA CONDIZIONE IF E VA NELLA ELSE NON RESTITUENDO I VALORI

**Comment by donatocatalano** [comment]
niente sta cosa non riesco a risolverla

**Comment by donatocatalano** [comment]
forse c'è qualche problema nel metodo ISCRIZIONIAUTORIZZATE perchè non le carica nemmeno nella pagina VEDIISCRIZIONI nell'area ISTRUTTORE

**Comment by giovannidefilippi** [comment]
Prima di metterci mano ne parliamo domani, così non capisco..

**Comment by donatocatalano** [comment]
QUI presenta diversi problemi di visualizzazione:

1) se lo stesso tesserato è iscritto a due discipline diverse non allinea gli eventi;
2) se non è stata ancora confermata l'iscrizione  stampa due volte "non sei abilitato" e stampa anche i tasti iscriviti che non dovrebbe stampare e se si preme indietro apre tre homepage perchè i tasti indietro appaiono sovrapposti a causa del primo ciclo for (con indice j)

**Comment by giovannidefilippi** [comment]
Lo sistemo domani, chiudo iusse, non l'ho letto ma preferisco riaffrontare il problema in toto...anche perchè nel frattempo è cambiata la logica dell'applicazione rispetto all'apertura del iusse...
