### ISSUE TITLE
Area Responsabile 

### ISSUE THREAD

**Issue by giovannidefilippi** [donatocatalano/centrosportivo#26]
ora accetta le modifiche prenotazioni e iscrizioni/pagamenti (scrive in due tabelle contemporaneamente)...
Faccio un push e stacco per un po'

**Comment by giovannidefilippi** [comment]
Ho modificato i nomi di alcune classi..

**Comment by donatocatalano** [comment]
si ma a me non funziona quando premo su autorizzazioni pagamenti ecc
edit: ho capito perchè...hai passato la data al metodo quindi mi dava errore siccome nel mio db non avevo messo data...sembra funzionare ora

**Comment by donatocatalano** [comment]
comunque se non ci sono pagamenti da autorizzare non carica pagina si blocca quando si preme sul bottone...
e una volta autorizzata iscrizione l'istruttore non riesce a vederla in "VEDIISCRIZIONI"

**Comment by donatocatalano** [comment]
era una system.out.println dimenticata lì...l'ho tolta e ho pushato
rimane problema:  una volta autorizzata iscrizione l'istruttore non riesce a vederla in "VEDIISCRIZIONI"

**Comment by giovannidefilippi** [comment]
Possiamo chiudere questa iusse ? Rimano solo da riempire meglio le schermate prenotazioni (mettere magari tutto l'evento/corso a cui ci si è prenotati) e Iscrizioni /pagamenti..

**Comment by giovannidefilippi** [comment]
L'area Responsabile è quasi ok
