### ISSUE TITLE
PROBLEMA IN AREA ISTRUTTORE - VIEW ELENCOISCRIZIONI

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#27]
forse il problema sta proprio nel metodo: una volta autorizzata iscrizione l'istruttore non riesce a vederla in "ELENCO ISCRIZIONI"

**Comment by donatocatalano** [comment]
forse l'istruttore dovrebbe vedere le iscrizioni agli eventi e non le iscrizioni alle discipline

**Comment by giovannidefilippi** [comment]
Ho modificato il frame in AreaPrenotazioni e sistemato.. sembra funzioni ma non mi fa fare il pull..

**Comment by donatocatalano** [comment]
fammi sapere se riesci a pullare le modifiche

**Comment by donatocatalano** [comment]
Buongiorno...Quindi questa si può chiudere?

**Comment by giovannidefilippi** [comment]
Si chiiudo
