### ISSUE TITLE
GitHub e Eclipse

### ISSUE THREAD

**Issue by giovannidefilippi** [donatocatalano/centrosportivo#3]
Per lavorare sul progetto in sincronismo con il repository in locale bisogna aprire un nuovo progetto da eclipse. Il progetto da aprire è proprio quello memorizzato nel repository locale. così le modifiche, che dalla working directory nella vista in basso non si possono fare, le accetta e si può anche lanciare l'applicazione. Giovedì chiarisco meglio.

**Comment by donatocatalano** [comment]
si penso di aver capito...proverò

**Comment by donatocatalano** [comment]
lms di git
