### ISSUE TITLE
AREA PRENOTAZIONE

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#31]
In area prenotazione ti esce "non è possibile inviare richiesta...riprovare più tardi" ???

**Comment by donatocatalano** [comment]
ma mancano ancora i metodi? solo i system.out.println ci sono?

**Comment by giovannidefilippi** [comment]
Mi sono incagliato sulle prenotazioni nuove rispetto a quelle gia' presenti...ora devo smettere ..ci guardo domani..

**Comment by giovannidefilippi** [comment]
Ora è ok..Ho fatto che : 
Alle prime prenotazioni metto  valida =1;
Le modifiche, valida =0 così il responsabile le accetta/non accetta
(il solo prb è che non si gestiscono le modifiche che tolgono la spunta , vede solo le aggiunte non cancella prenotazioni. )
Prova questa versione e dimmi

**Comment by giovannidefilippi** [comment]
chiudo

**Comment by giovannidefilippi** [comment]
chiudo
