### ISSUE TITLE
problema descrizione

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#5]
Stavo aggiornando i campi descrizione per le discipline ma mi sono accorto che il testo non va a capo in automatico e nel database non si può dire di andare  a capo dopo un punto specifico.

**Comment by giovannidefilippi** [comment]
Inserito layout tipo box al panel che contiene la jLabel descrizione .Inserito stile padding.

**Comment by donatocatalano** [comment]
Si questo risolve il problema per il testo inserito nel codice java...ma quando il testo deve essere preso dal database campo descrizione non si può gestire...lo prende come sta nel database e non si può modificare

**Comment by giovannidefilippi** [comment]
Il testo è una stringa che possiamo manipolare come ci pare...

**Comment by donatocatalano** [comment]
Ma la stringa la cattura direttamente dal database...c'é qualche metodo che si può inserire nella chiamata al database per modificare la stringa richiamata?

**Comment by donatocatalano** [comment]
Ho pensato di modificare totalmente pagina info disciplina...facendo la descrizione disciplina solo di un rigo cosi non abbiamo il problema dell'andare a capo e anche l'immagine viene ingrandita...in più ho fatto pagina feedback...e feedbacktesserato...
Ho lasciato infodisciplinatesserato con la vecchia visualizzazione per avere un confronto su come era prima...
Vediamo domani insieme che te ne pare

**Comment by giovannidefilippi** [comment]
Ok 

Giovanni

**Comment by giovannidefilippi** [comment]
Chiudo lo issue.
