### ISSUE TITLE
scrollpane

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#6]
Ho inserito ScrollPane in AreaIscrizioni (tesserato) per caricare lì tutte le discipline con livelli e turni annessi...
Stessa cosa ho fatto nelle aree riservate istruttore e responsabile...
PROBLEMA
Ho paura che serva una mouselistener e una textarea per gestire lo scrollpane...
Insomma sembra che sia leggermente complicato usarlo...ho letto qualcosa ma ad ora mi sono fermato...

**Comment by giovannidefilippi** [comment]
Lo scrollPane è andato....
