### ISSUE TITLE
problema inserimento nuovo evento

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#7]
Funziona per nuovo corso ma non funziona per nuovo evento...ho provato a fare un unico ascoltatore per due classi...forse è per questo...inoltre vede solo la data di inizio e non la data di fine

**Comment by donatocatalano** [comment]
ho visto sistemazione data...non sapevo che gregorian calendary fosse da trattare in quel modo...bene così!
per quanto riguarda il problema nuovo evento a me rimane...non so se lo avevi sistemato ed è stato un problema del pull...penso che ora staccherò...

**Comment by donatocatalano** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "09-10-20102020"  per nuovo evento

**Comment by giovannidefilippi** [comment]
Nell'ascoltatore conferma evento era rimasta la doppia data...ora l'ho tolta

**Comment by donatocatalano** [comment]
io non ce l'ho eppure non funziona...fai un push...così io pullo
