### ISSUE TITLE
Area Istruttore

### ISSUE THREAD

**Issue by giovannidefilippi** [donatocatalano/centrosportivo#8]
Bisogna passare istruttore per inserire id nell'evento. Il tipoEvento nel FormCorso è inutile(si passa il numero 3 nel db) mentre x la disciplina meglio un menù a tendina che pesca dalle discipline..stessa cosa per lo spazio in cui avviene il corso...Situazione simile per l'evento gara/stages

**Comment by giovannidefilippi** [comment]
Ora pausa x me  ..

**Comment by donatocatalano** [comment]
ok non avevo pensato ai menù a tendina...poi vedo come si fanno...o li fai tu? comunque si meglio così gli mettiamo il testo altrimenti dovremmo gestire la conversione codice (spazio, disciplina ecc) con il testo inserito durante la compilazione...non so se mi sono spiegato...XD

**Comment by donatocatalano** [comment]
stavo vedendo i menu' a tendina...dovrebbe essere JComboBox...

si dovrebbe usare tipo così:

String [] numeri = {"10", "20", "30", "40"};
public JComboBox luogo_box= new JComboBox(String <E>numeri);

solo che sbaglio qualcosa nelle parentesi del combobox

**Comment by donatocatalano** [comment]
comunque ho visto le modifiche in disciplina...non sono sicuro di averle capite...visto che funzionava...ora non mi funziona più catalogo discipline in area responsabile...(avevo creato il metodo ieri che tu oggi mi hai cambiato mi pare)

comunque adesso mi fermo perchè dopo aver fatto il pull non mi funziona niente...in quanto manca qualche cosa...poi quando finisci e le tue modifiche funzionano avvisami che faccio il pull e provo...
mi metto a fare il collegamento tra le finestre su carta visto che me lo avevi chiesto

**Comment by giovannidefilippi** [comment]
finito

**Comment by donatocatalano** [comment]
inseriti menu a tendina e passato istruttore...non so come far prendere dall'ascoltatore i valori selezionati dal combobox

**Comment by donatocatalano** [comment]
questo risolto
chiudo
