### ISSUE TITLE
problema elenco utenti in attesa di registrazione

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#9]
Non capisco perchè quando me li carica non mette un utente per rigo...come ad esempio per il catalogo discipline...forse perchè discipline viene passato per singola disciplina mentre utente li prende tutti?

ho fatto ascoltatore conferma registrazione per il bottone in questa pagina e creato i metodi...(che vanno controllati perchè sicuro stanno sbagliati) ma soprattutto non so come "attaccare" l'ascoltatore al bottone conferma sempre nella pagina catalogo

**Comment by giovannidefilippi** [comment]
No perché il panel delle discipline ha un layout diverso mi pare box layout..

Giovanni

**Comment by donatocatalano** [comment]
nono sono tutti uguali...apposta lo sto dicendo...pulla

**Comment by donatocatalano** [comment]
sistemato
